name: Build release & deploy

on:
  repository_dispatch:
    types: [deploy-command]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      - name: Get the target branch name
        id: vars
        run: |
          branch=$(curl -v -H "Accept: application/vnd.github.sailor-v-preview+json" -u ${{ secrets.REPO_ACCESS_TOKEN }} ${{ github.event.issue.pull_request.url }} | jq '.head.ref' | sed 's/\"//g')
          if [[ -z "$branch" ]]; then branch=${GITHUB_REF}; fi
          echo ::set-output name=branch::$branch
      - name: echo upstream branch
        run: |
          echo ${{ steps.vars.outputs.branch }}